language: node_js
node_js: 14
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  github_url: github.schibsted.io
  local_dir: ./out
  email: travis@schibsted.com
  name: Travis CI
  on:
    branch: master
group: container
